### ISSUE TITLE
getResources fails to load in MODX 3.0.0

### ISSUE THREAD

**Issue by visualgui** [opengeek/getResources#107]
getResources seems to buffer and get a timeout; therefore, only load a blank page.

Here's the code: 

`[[getResources? &showHidden=`1` &includeTVs=`1` &tvPrefix=`` &limit=`0` &sortbyTV=`lname` &sortdirTV=`ASC` &parents=`1234` &depth=`1` &tpl=`faculty_list` &sortBy=`lname` &sortDir=`ASC` &display=`all` &filter=`hide_all,1,2`]]
`

**Comment by visualgui** [comment]
I tried it again using a resource (directory) with lesser children (9 instead of hundreds), getResource populated the list.

This one has hundreds of items: https://c0791.paas2.tx.modxcloud.com/faculty/directory/fulltime/
This one only has 9 items: https://c0791.paas2.tx.modxcloud.com/faculty/directory/emeritus/

**Comment by jaygilmore** [comment]
I'm wondering if you're seeing any errors in your PHP or server error logs? Is it possible your query not completing? 

Also, for clarity, I reformatted the Snippet call to be easier to read. (Multiline code blocks are either indented or in triple backticks)

```php
[[getResources? 
    &showHidden=`1`
    &includeTVs=`1`
    &tvPrefix=`` 
    &limit=`0` 
    &sortbyTV=`lname` 
    &sortdirTV=`ASC` 
    &parents=`1234` 
    &depth=`1` 
    &tpl=`faculty_list` 
    &sortBy=`lname` 
    &sortDir=`ASC` 
    &display=`all` 
    &filter=`hide_all,1,2`
]]
```

**Comment by visualgui** [comment]
This is the exact code:

```
[[getResources? 
	&showHidden=`1` 
	&includeTVs=`1` 
	&tvPrefix=`` 
	&limit=`42` 
	&sortbyTV=`lname` 
	&sortdirTV=`ASC` 
	&parents=`5842` &
	depth=`1` 
	&tpl=`ditto.faculty_list_2015` 
	&sortBy=`lname` 
	&sortDir=`ASC` 
	&display=`all` 
	&filter=`hide_all,1,2`
]]
```

Here's the working page: https://ho8tajk7.modx.dev/faculty/directory/fulltime/

Notice the `&limit=`42``. When I set `&limit=`0``, the page would be blank. Is there some PHP setting that I need to change?

**Comment by visualgui** [comment]
Also, we're powered by MODX Cloud, MODX 3.0.1pl, and php 8.0.

**Comment by jaygilmore** [comment]
@visualgui, What version of getResources are you running? Have you run it with no `tpl` defined and 

    &debug=`1`

It won't output debug info unless the tpl is not defined. The easiest way to do this is to add a character between the `&` and the `tpl`, i.e., `&_tpl` as MODX won't match that value. What will result is the array of the results if MODX was able to build them along with all the defined properties in the gR call.

**Comment by Mark-H** [comment]
That's an awfully specific number it's failing at... Does it work with 100, 1000, etc? How many actual records do you have?

In MODX cloud you can find the PHP log one directory up from your webroot (via FTP/SSH) in ~/log or ~/logs.

**Comment by jaygilmore** [comment]
@Mark-H I was asking about the gR version because if not using the latest, there is a PHP 8 incompatibility from #106 

Also, do you know what that `&filter` does? I don't know of this as a property. I'm only familiar with `tvFilter`.  I've looked in the [docs](https://docs.modx.com/3.x/en/extras/getresources) but found nothing.

**Comment by visualgui** [comment]
@jaygilmore, we’re using getResources 1.7.0-pl. When I run the &debug=`1` with the &_tpl, it gave me a blank page.

@Mark-H, It only works up to 42. I tried run 43, 50, 100 and nothing would work. The list is about 100 items.

Error Logs:


`[26-Apr-2022 19:04:40 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "inc" in /www/assets/snippets/inc/inc.class.php:2
Stack trace:
#0 /www/core/cache/includes/elements/modsnippet/1320.include.cache.php(7): include()
#1 /www/core/model/modx/modscript.class.php(76): include('...')
#2 /www/core/model/modx/modparser.class.php(537): modScript->process()
#3 /www/core/model/modx/modparser.class.php(251): modParser->processTag()
#4 /www/core/model/modx/modtemplatevar.class.php(151): modParser->processElementTags()
#5 /www/core/model/modx/modparser.class.php(528): modTemplateVar->process()
#6 /www/core/model/modx/modparser.class.php(251): modParser->processTag()
#7 /www/core/model/modx/modchunk.class.php(116): modParser->processElementTags()
#8 /www/core/model/modx/modparser.class.php(499): modChunk->process()
#9 /www/core/model/modx/modparser.class.php(251): modParser->processTag()
#10 /www/core/model/modx/modtemplate.class.php(126): modParser->processElementTags()
#11 /www/core/model/modx/modresource.class.php(513): modTemplate->process()
#12 /www/core/model/modx/modresource.class.php(494): modResource->process()
#13 /www/core/model/modx/modresponse.class.php(62): modResource->prepare()
#14 /www/core/model/modx/modrequest.class.php(138): modResponse->outputContent()
#15 /www/core/model/modx/modrequest.class.php(122): modRequest->prepareResponse()
#16 /www/core/model/modx/modx.class.php(1461): modRequest->handleRequest()
#17 /www/index.php(54): modX->handleRequest()
#18 {main}
  thrown in /www/assets/snippets/inc/inc.class.php on line 2`

`[09-May-2022 18:11:59 UTC] PHP Fatal error:  Uncaught Error: Call to a member function toArray() on null in /www/core/components/versionx/model/versionx.class.php:321
Stack trace:
#0 /www/core/components/versionx/elements/plugins/versionx.plugin.php(62): VersionX->newSnippetVersion()
#1 /www/core/cache/includes/elements/modx/revolution/modplugin/250.include.cache.php(6): include('...')
#2 /www/core/src/Revolution/modScript.php(88): include('...')
#3 /www/core/src/Revolution/modX.php(1706): MODX\Revolution\modScript->process()
#4 /www/core/src/Revolution/Processors/Model/CreateProcessor.php(192): MODX\Revolution\modX->invokeEvent()
#5 /www/core/src/Revolution/Processors/Model/CreateProcessor.php(90): MODX\Revolution\Processors\Model\CreateProcessor->fireAfterSaveEvent()
#6 /www/core/src/Revolution/Processors/Processor.php(189): MODX\Revolution\Processors\Model\CreateProcessor->process()
#7 /www/core/src/Revolution/modX.php(1771): MODX\Revolution\Processors\Processor->run()
#8 /www/core/src/Revolution/modConnectorResponse.php(151): MODX\Revolution\modX->runProcessor()
#9 /www/core/src/Revolution/modConnectorRequest.php(89): MODX\Revolution\modConnectorResponse->outputContent()
#10 /www/core/src/Revolution/modConnectorRequest.php(77): MODX\Revolution\modConnectorRequest->prepareResponse()
#11 /www/connectors/index.php(79): MODX\Revolution\modConnectorRequest->handleRequest()
#12 {main}
  thrown in /www/core/components/versionx/model/versionx.class.php on line 321`

**Comment by opengeek** [comment]
This seems unrelated to getResources itself. Re-open if a specific getResources issue has been identified.
