### ISSUE TITLE
New package version for PHP 8.x

### ISSUE THREAD

**Issue by wuuti** [opengeek/getResources#110]
The latest released version 1.7.0 is incompatible with PHP 8.x, because of the wrong order of arguments for implode used in the snippet. I see this was already fixed with https://github.com/opengeek/getResources/commit/09ddb046f42fe5b01f1ad95bcff0c27911bb5975, but no new version was created.

Please provide a new package version so that extra management shows an update here.

**Comment by opengeek** [comment]
Done
