### ISSUE TITLE
Reading symlinks and their values

### ISSUE THREAD

**Issue by bertoost** [opengeek/getResources#28]
For a project we have made a list with resources inside a category page. In an other category page we have made a symlink to a resource somewhere else in the website. This works great but only the the overview of symlinks doesn't have all information from the symlink page.

What I would like to have is all information (like fields and tvs) from the resource where the symlink was made to. I hope you will understand and maybe this is a good fix for working with symlinks

For now I have manually fixed this in the getresources snippet

**Comment by yoleg** [comment]
Just my 2¢: If you add snippet parameters such as &loadSymlinkFields and &loadSymlinkTVs, it would avoid the overhead for anyone who does not want it. Loading all of the fields at once in getResources is much less overhead than output filters loading each field and TV separately.
