### ISSUE TITLE
Bug with "limit=0" and "offset=x"?

### ISSUE THREAD

**Issue by mindeffects** [opengeek/getResources#92]
Hi Jason,
it seems that the "limit" parameter, when set to "0", overwrites any "offset" parameter. I allways thought of "limit" as "the number of elements starting to count at the offset", like "start at element 6 and continue until you reach the end". This is not possible with limit=0 – but with limit=9999 which is somehow "bad style", right? Whats the bigges possible integer? ;-)
cheers
Oliver

**Comment by jcamachott** [comment]
Bug experienced! Hopefully will be fixed.

**Comment by bYemma** [comment]
Bug also experienced.

Oliver, thank you for the workaround while it's not fixed.

**Comment by opengeek** [comment]
You cannot use limit=0. That is simply an invalid limit.
